---
product-name: p-healthwatch2-pks-exporter
network-properties:
  network:
    name: pks
  service_network:
    name: services
  other_availability_zones:
  - name: ((availability_zones.0))
  - name: ((availability_zones.1))
  - name: ((availability_zones.2))
  singleton_availability_zone:
    name: ((availability_zones.0))
product-properties:
  .bosh-health-exporter.health_check_az:
    value: ((availability_zones.0))
