---
pivnet-product-slug: p-healthwatch

file-glob: "p-healthwatch-pas-exporter*.pivotal"
product-version: ((healthwatch-version))
stemcell-iaas: vsphere

pivnet-api-token: ((tile_config.pivnet_refresh_token))