---
pivnet-product-slug: p-healthwatch

file-glob: "healthwatch-2.3.1-build.47.pivotal"
product-version: ((healthwatch-version))
stemcell-iaas: vsphere

pivnet-api-token: ((tile_config.pivnet_refresh_token))