# assuming single pipeline per foundation.
# cred names are reused, but exist on unique pipeline paths
opsman-configuration:
  vsphere:
    vcenter:
      url: ((vcenter.url))
      username: ((vcenter.user))
      password: ((vcenter.password))
      datastore: vsanDatastore
      datacenter: dc01
      #resource_pool: /Datacenter/host/Cluster
      insecure: 1
    ssh_public_key: ((tile_config.scp_private_key))
    disk_type: thin
    private_ip: 194.168.64.31
    dns: 192.168.64.1
    ntp: 192.168.64.1
    hostname: ((opsman_url))
    network: "VM Network"
    netmask: 255.255.255.0
    gateway: 194.168.64.1
    memory: 8
    cpu: 4