# assuming single pipeline per foundation.
# cred names are reused, but exist on unique pipeline paths
opsman-configuration:
  vsphere:
    vcenter:
      url: ((vcenter.url))
      username: ((vcenter.user))
      password: ((vcenter.password))
      datastore: vsanDatastore
      datacenter: dc01
      resource_pool: TASrp 
      insecure: 1
    ssh_public_key: ((tile_config.scp_private_key))
    disk_type: thin
    private_ip: 192.168.64.100
    netmask: 255.255.255.0
    dns: 192.168.64.1
    gateway: 192.168.64.1
    ntp: 192.168.64.1
    hostname: ops-manager
    network: dvVMNetwork
    memory: 8
    cpu: 4