product-name: pivotal-mysql
product-properties:
  .properties.allow_lower_case_table_names_via_config_param:
    value: false
  .properties.audit_logging_enabled:
    value: false
  .properties.backups_selector:
    selected_option: scp
    value: SCP Backups
  .properties.backups_selector.scp.cron_schedule:
    value: 0 11 * * *
  .properties.backups_selector.scp.destination:
    value: /tmp
  .properties.backups_selector.scp.key:
    value:
      secret: ((tile_config.scp_private_key))
  .properties.backups_selector.scp.port:
    value: 22
  .properties.backups_selector.scp.server:
    value: pn50.diggity00.net
  .properties.backups_selector.scp.user:
    value: mdolan
  .properties.binlog_space_limit_enabled:
    value: false
  .properties.canary_instances:
    value: 0
  .properties.enable_lower_case_table_names:
    value: false
  .properties.enable_read_only_admin:
    value: false
  .properties.enable_secure_binding_credentials:
    value: false
  .properties.enforce_client_tls:
    value: false
  .properties.global_recipient_email:
    value: mike_dolan@broadcom.com
  .properties.global_service_instance_limit:
    value: 20
  .properties.local_infile:
    value: false
  .properties.mysql_metrics_frequency:
    value: 30
  .properties.off_platform_access_selector:
    selected_option: disabled
    value: disabled
  .properties.plan1_selector:
    selected_option: single_node
    value: single_node
  .properties.plan1_selector.single_node.access_dropdown:
    value: enable
  .properties.plan1_selector.single_node.az_multi_select:
    value:
    - az1
  .properties.plan1_selector.single_node.description:
    value: This plan provides a small dedicated MySQL instance.
  .properties.plan1_selector.single_node.name:
    value: db-small
  .properties.plan1_selector.single_node.paid_plan:
    value: false
  .properties.plan1_selector.single_node.version_dropdown:
    value: "8.0"
  .properties.plan2_selector:
    selected_option: single_node
    value: single_node
  .properties.plan2_selector.single_node.access_dropdown:
    value: enable
  .properties.plan2_selector.single_node.az_multi_select:
    value:
    - az1
  .properties.plan2_selector.single_node.description:
    value: This plan provides a medium dedicated MySQL instance.
  .properties.plan2_selector.single_node.name:
    value: db-medium
  .properties.plan2_selector.single_node.paid_plan:
    value: false
  .properties.plan2_selector.single_node.version_dropdown:
    value: "8.0"
  .properties.plan3_selector:
    selected_option: single_node
    value: single_node
  .properties.plan3_selector.single_node.access_dropdown:
    value: enable
  .properties.plan3_selector.single_node.az_multi_select:
    value:
    - az1
  .properties.plan3_selector.single_node.description:
    value: This plan provides a large dedicated MySQL instance.
  .properties.plan3_selector.single_node.name:
    value: db-large
  .properties.plan3_selector.single_node.paid_plan:
    value: false
  .properties.plan3_selector.single_node.version_dropdown:
    value: "8.0"
  .properties.plan4_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan5_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan6_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan7_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan8_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan9_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan10_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan11_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan12_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan13_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan14_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan15_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan16_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan17_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan18_selector:
    selected_option: inactive
    value: Inactive
  .properties.request_timeout:
    value: 120
  .properties.simultaneous_upgrades:
    value: 1
  .properties.userstat:
    value: false
  .properties.wait_timeout:
    value: 28800
network-properties:
  network:
    name: vlan64
  other_availability_zones:
  - name: az1
  service_network:
    name: vlan64
  singleton_availability_zone:
    name: az1
resource-config:
  dedicated-mysql-broker:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
errand-config:
  delete-all-service-instances-and-deregister-broker:
    pre-delete-state: true
  recreate-all-service-instances:
    post-deploy-state: false
  register-broker:
    post-deploy-state: true
  smoke-tests:
    post-deploy-state: true
  upgrade-all-service-instances:
    post-deploy-state: true
  validate-before-upgrade-instances:
    post-deploy-state: true
syslog-properties:
  address: null
  custom_rsyslog_configuration: null
  enabled: false
  environment: null
  forward_debug_logs: false
  permitted_peer: null
  port: null
  queue_size: null
  ssl_ca_certificate: null
  tls_enabled: false
  transport_protocol: tcp

